### ISSUE TITLE
Any plans to use AKS/K8s?

### ISSUE THREAD

**Issue by stevetayloruk** [Azure/Unreal-Pixel-Streaming#16]
Question.

Will this work in AKS and if so, is there any plans to port/support it?

Thanks

Steve

**Comment by microsoftman** [comment]
Hi Steve, we originally considered AKS as an option, but decided to keep it simpler with VMSS nodes to reduce the added complexity/ramp up for those not strong on AKS. Possibly in the future this could be added if we find enough adoption to justify the work. The team hasn't tried it on AKS, but assuming getting the NVIDIA GRID drivers working on a Windows node with containers within AKS is possible, could be a an option perhaps.  Let us know if you take a stab at it--would be good to validate.

**Comment by stevetayloruk** [comment]
Thanks for the quick reply.  

How far along are you getting to work on Linux? 

Thanks

Steve

**Comment by microsoftman** [comment]
So we don't have any resources looking into that, but if you are motivated to try it out and share with us your learnings we might be able to push on that option for the future.
