### ISSUE TITLE
onClientDisconnect does not seem to work

### ISSUE THREAD

**Issue by erik-jansen** [Azure/Unreal-Pixel-Streaming#22]
When a client disconnects from the UE4 app, it triggers the onClientDisconnect event. That should then call the powershell script to kill and restart the node and UE4 processes. That seems to be broken at the moment.

**Comment by apichugin81** [comment]
I have the same problem. It seems cirrus.js works uncorrectly with function restartUnrealApp()

**Comment by YvesCandel** [comment]
Is this why it keeps showing "All ... Cirrus servers are in use. Retrying in 10 seconds." ?

**Comment by YvesCandel** [comment]
Doesn't matter if I spin up 10 instances, they're all continually in use...

**Comment by microsoftman** [comment]
Hi @YvesCandel, that shouldn't affect your issue you are seeing as this would only affect new users logging on and just picking up the last place in the app the previous user stopped it.  For your issue, If you manually go to the Signaling Server URL for the different instances, are you able to connect fine?  Usually we've seen that issue you have if there is something wrong on the Signaling Server/App side. Also, keep in mind, the default wait time is 45 seconds between when an instance becomes available and when the Matchmaker will redirect to that one (to avoid multiple people getting redirected before someone hits play and locks the session).

**Comment by YvesCandel** [comment]
Hi @microsoftman, thanks for your response. If I go straight to the IP address of the VM Scale set, I do actually get the Unreal Streaming screen with "Click to start", but when I then click it just keeps showing "Disconnected: Streamer is not connected" and goes back to "Click to start".

**Comment by microsoftman** [comment]
> Hi @microsoftman, thanks for your response. If I go straight to the IP address of the VM Scale set, I do actually get the Unreal Streaming screen with "Click to start", but when I then click it just keeps showing "Disconnected: Streamer is not connected" and goes back to "Click to start".

Hi @YvesCandel, thanks for checking -- that makes sense, as if the MatchMaker can't connect to the stream and it won't play, it will think it has a stream open but that it's not available to use. Can you perhaps login to an instance VM on the VMSS and look at the logs?  You should also check in Task Manager if the NodeJS app is running for Signaling Server (which it sounds like it is), and then check if the Unreal 3D app is running (likely this is the issue).  There is a logs folder under C:\gaming where you can see what might be happening on startup of the VM.

**Comment by YvesCandel** [comment]
Hi @microsoftman,

It seems the Unreal 3D App just won't run. If I check the logs folder I find the following:

```
startingVMSS
current folder :C:\Unreal\
started :C:\Unreal\PixelStreamingDemo.exe
current folder :C:\Unreal\Engine\Source\Programs\PixelStreaming\WebServers\SignallingWebServer
Config.json :@{UseFrontend=False; UseMatchmaker=True; UseHTTPS=False; UseAuthentication=False; LogToFile=True; HomepageFile=/public/player.html; AdditionalRoutes=; EnableWebserver=True; MatchmakerAddress=<redacted>; MatchmakerPort=9999; PublicIp=; HttpPort=80; HttpsPort=443; StreamerPort=8888; subscriptionId=<redacted>; resourceGroup=<redacted>; virtualMachineScaleSet=<redacted>; appInsightsInstrumentationKey=<redacted>; unrealAppName=PixelStreamingDemo; region=northeurope}
Public IP Address for lookup of FQDN: <redacted>
Success in getting FQDN: <redacted>.northeurope.cloudapp.azure.com
Started vmss sucessfully runAzure.bat
```

With no further errors, If I try to start it up myself by either clicking it or running it from Powershell with the following cmd:

```
.\PixelStreamingDemo.exe -AudioMixer -PixelStramingIP=localhost -PixelStreamingPort=8888 -RenderOffScreen -WinX=0 -WinY=0 -Width=1920 -Height=1080 -Windowed -ForceRes
```

...it's the same. I don't even see it showing up in the task manager. Like it instantly quits and I can't figure out why.

This is probably the reason the whole terraform thing completes fine, but I can't manage to connect to it. Have you tried running the terraform yourself recently?

**Comment by microsoftman** [comment]
Hi @YvesCandel, thanks for the details and degugging. Instead of using the command to run the demo, can you just RDP into the VMSS instance that has the UE4 app and double click the PixelStreamingDemo.exe file and see if it runs normally?  If it can't run it should bring up a popup with the error.  Usually if this happens it is becuase the ThirdParty\ DLLs weren't added into the repo (we don't have rights to distribute those).  Can you verify on the VMSS instance if you also have all the folders\dlls in the ThirdParty folder per the documentation on step 3 here under Unreal Engine App:  https://docs.microsoft.com/en-us/gaming/azure/reference-architectures/unreal-pixel-streaming-at-scale#unreal-3d-app

Otherwise, if it's still not working, we can setup a screen sharing session if that would help.  @erik-jansen is in Europe as well. Also, are you just trying to run our PixelStreamingDemo.exe app or did you add your own UE4 app?

**Comment by YvesCandel** [comment]
Hi @microsoftman , thanks for your responses. We've investigated a lot more things and eventually found that our own UE4 project creates an "alert" when it's started up with the following error:

```
XAudio2.7 is not installed. Make sure you have XAudio 2.7 installed. XAudio 2.7 is available in the DirectX End-User Runtime (June 2010)
```

...and this alert seems to block everything. If I RDP into the VMSS instances, and kill the Unreal process and restart it, I have the opportunity to click "OK" on this alert and the game will continue to keep running and I can connect through the Traffic Manager/Matchmaker without any issues. I've been trying to get rid of this "alert" for a while now but cannot seem to fix it. Installing the DirectX End-User Runtime (June 2010) doesn't help with removing this alert. Any suggestions and is this something you've encountered too?

Thanks
