### ISSUE TITLE
Missing XAudio 2.7 on msftpixelstreaming image

### ISSUE THREAD

**Issue by YvesCandel** [Azure/Unreal-Pixel-Streaming#26]
We found that our own UE4 project creates an "alert" when it's started up with the following error:

```
XAudio2.7 is not installed. Make sure you have XAudio 2.7 installed. XAudio 2.7 is available in the DirectX End-User Runtime (June 2010)
```

...and this alert seems to block everything. If we RDP into the VMSS instances, and kill the Unreal process and restart it, we have the opportunity to click "OK" on this alert and the game will continue to keep running and we can connect through the Traffic Manager/Matchmaker without any issues. We've been trying to get rid of this "alert" for a while now but cannot seem to fix it. Installing the DirectX End-User Runtime (June 2010) doesn't help with removing this alert. 

Any suggestions on this? We don't run into this issue on a manually created Win11 VM, but with the microsoft-agci-gaming:msftpixelstreaming:nvidia image we do get this, and we believe it's strongly tied to this repository right?

It seems blocking to get our own UE4 project up and running and we haven't found any solution yet.

**Comment by microsoftman** [comment]
Hi @YvesCandel, yes the solution to this issue should be as I mentioned in the previous thread about needing to add the ThirdParty\ folder and it's contents which includes dlls for things like DirectX and other depedencies which we don't have permissions to deploy those binaries.  Can you review the documentation here and verify that your forked repo has those ThirdParty folder and binaries checked in and get deployed to the VMSS instances? https://docs.microsoft.com/en-us/gaming/azure/reference-architectures/unreal-pixel-streaming-at-scale#unreal-3d-app

**Comment by YvesCandel** [comment]
Hi, Thanks for your response. We do indeed have all the ThirdParry\ folder contents in place... the folder with everything works fine on a different VM -- it just doesn't on the microsoft-agci-gaming:msftpixelstreaming:nvidia image VM inside the scale set.

**Comment by microsoftman** [comment]
Ok thanks for confirming, can you remind me which version of Unreal you are using, 4.27.1 perhaps?  We can validate again with the exact version you are using, but should be 4.27 and above.

**Comment by YvesCandel** [comment]
We're on version 4.27.2

**Comment by khaines** [comment]
> We're on version 4.27.2

I will setup an environment using this version to try and reproduce the results you found @YvesCandel.

**Comment by YvesCandel** [comment]
Hi guys,

Sorry, but we've found the issue. By default if you copy over your ThirdParty folder, everything commits except for the \Windows\ folder because it contains a subfolder named x64, and folders with that name are gitignored by your repository. So there was a file missing there which was causing this error. Thanks for the advice!

**Comment by microsoftman** [comment]
Thanks for the update @YvesCandel, we will make sure we add that piece to the documentation about making sure those aren't ignored in the repo.  Much appreciated!
