### ISSUE TITLE
How many instances can one server run the PixelStreamer run on Multiplayer?

### ISSUE THREAD

**Issue by adshodgson** [Azure/Unreal-Pixel-Streaming#29]
Hi there, thanks so much for providing such great documentation,

We've been investigating PixelStreaming solutions for a while, but currently unsure how to handle the Multiplayer / Matchmaking aspect (With a unique instance of unreal).

From my understanding - with the current PixelStreaming solutions the hosted cloud Instance would auto scale appropriately depending on how many users are joining for a unique session/experience, however how does this work with lets say 5,000 users? 

How many GPUs might need to be created in order to facilitate that type of demand and/or is this even achievable with the Azure setup?

Kind regards

**Comment by microsoftman** [comment]
Hi @adshodgson, thanks for the feedback on this. So the current Pixel Streaming deployment uses Virtual Machine Scale Sets, which has a [limit ](https://docs.microsoft.com/en-us/azure/virtual-machine-scale-sets/overview#:~:text=Scale%20sets%20support%20up%20to,limit%20is%20600%20VM%20instances.) of 1,000 VMs per VMSS (600 VMs if using a managed image). If you are spinning up the game in multiple regions, like what is built into the Terraform template, you could have those split across multiple regions or even tweak the template to allow it to spin up multiple VMSS instances/stream in the same region (by default it assumes 1 deployment per region). Depending on the complexity of your  3D app, you could have more than 1 stream per GPU; however, we recommend you first test that on a regular VM in Azure to watch for GPU/CPU spikes, and play with FPS and Resolution configurations to see what you are comfortgable with (e.g., 720p with 30fps can help to get more streams). We recommend at least a NVv3 series GPU, as the older NV series have an older CPU and you gain around 30% or so with the NVv3 CPU perf.
