### ISSUE TITLE
unreal pixel streaming at scale 

### ISSUE THREAD

**Issue by Camouflagestudios** [Azure/Unreal-Pixel-Streaming#31]
We have packaged a project for pixel streaming in Azure .
We succeeded to deploy in azure using single VM , matchmaker for one region and the a traffic manager with multi region
We tried the unreal pixel streaming at scale available on azure market place .
We followed the tutorial in the documentation and each time the deployment fails with error saying that the application insight doesn't support the classic mode of the resource group and it needs to be of workspace base, any clues??

**Comment by microsoftman** [comment]
@Camouflagestudios thanks for reaching out on this. I just tried to deploy to East US and was successful -- can you try East US as a test and see if this issue is still happening and something specific to your settings used? Also, which region(s) did you try, I will try your region as well to verify.

**Comment by Camouflagestudios** [comment]
Well . I guess we tried US west  . And we tried many regions    if you know a specific regions tha works with classic resource group . Tell me

**Comment by Camouflagestudios** [comment]
But my application should be running mostly from egypt , middle east and europe

**Comment by microsoftman** [comment]
@Camouflagestudios can you try East US? I tried it earlier today with the[ Azure Marketplace solution](https://azuremarketplace.microsoft.com/en-us/marketplace/apps/epicgames.unreal-pixel-streaming?tab=Overview) and it worked fine for me. If it doesn't work, I'd like to get the exact settings/configurations you chose to see if I can reproduce it with you. This shouldn't be happening in any region, but I want to see if you get the same issue in East US, which might mean something different is happening from your Azure subscription.

**Comment by microsoftman** [comment]
So looking into this more, it appears you are using Terraform from this repo which uses the older style of classic App Insights that some Azure regions are now not allowing. We will look to fix that for the Terraform version, but in the meantime please use the Azure Marketplace version which uses the latest workspaces for App Insights and deploys fine.

**Comment by Camouflagestudios** [comment]
> So looking into this more, it appears you are using Terraform from this repo which uses the older style of classic App Insights that some Azure regions are now not allowing. We will look to fix that for the Terraform version, but in the meantime please use the Azure Marketplace version which uses the latest workspaces for App Insights and deploys fine.

We are using the azure market place unreal pixelstreaming version .

**Comment by microsoftman** [comment]
Intersting, we tried East US, West Europe and SE Asia and all were successful in our tests -- did you try East US by chance yet to see if it still does the same thing there? Can you send me the "Inputs" of the deployment (either screenshots or printing to PDF) so I can try and match your exact settings to see if I can repro this? Also, if you have a time slot on Monday to do a screen share I can send out a meeting invite as well.

**Comment by Camouflagestudios** [comment]
Monday for zoom or google meet will be ok 
You can use this email 
Eldeebehab77@gmail.com

**Comment by Camouflagestudios** [comment]
Here are the images :
here to create a new deployment using the unreal pixel streaming in azure market place
![Screenshot 2022-08-27 153218](https://user-images.githubusercontent.com/111067796/187033436-ba740c47-d1df-48fa-b4dd-b8e9e7b52f76.png)
we tried East us2 as app deployment Region but there was no available GPU vms for UE app our subscription in this region ??? 
![east us2](https://user-images.githubusercontent.com/111067796/187033491-2a31da4f-1239-4227-92c4-30335d4c95d2.png)
we kept trying regions until we found that west us 3 has available vms for both ue app and matchmaker 
![west us](https://user-images.githubusercontent.com/111067796/187033617-607b9f97-6019-4563-aa98-4d879b4ef119.png)

then we finished the page required data  we went to load package .
![load package](https://user-images.githubusercontent.com/111067796/187033706-07b25562-7263-4ec6-a17b-47ce902f1d13.png)
we created storage and container and uploaded our package
![pakage resource group](https://user-images.githubusercontent.com/111067796/187033741-e588827d-329a-4869-a911-7050a1b758eb.png)
here is the container >>>>
![package container](https://user-images.githubusercontent.com/111067796/187033749-6b9f7c30-f91c-4711-8a1c-0167520519b2.png)
here is the package compressed file 
![package file](https://user-images.githubusercontent.com/111067796/187033756-539e68b1-b48f-471d-831b-d101a05c636b.png)
here is the exe file name 
![file name](https://user-images.githubusercontent.com/111067796/187033768-c96d7f38-4422-4961-bed2-c923c073fa92.png)
 after that we assigned the credentials , then we left all other tabs to default ( scale , stream config .. ETC )
the we pressed review  and create , and the validation passed >>>

![validation 03](https://user-images.githubusercontent.com/111067796/187033818-628624c4-186a-4962-bdb7-45b282cb6e20.png)
![validation 02](https://user-images.githubusercontent.com/111067796/187033820-79ccee1a-3124-439b-8fe7-92daa51d548b.png)
![validation 01](https://user-images.githubusercontent.com/111067796/187033821-e5ee77fe-16ce-457b-a91e-cc8025c40c3d.png)
 then we started to deploy >>
the deployment failed  >>
![deployment faild](https://user-images.githubusercontent.com/111067796/187033839-50b20881-45dc-4a41-b852-cca3700581ba.png)

![deployment fail 04](https://user-images.githubusercontent.com/111067796/187033832-4e6d8772-5d72-4d99-8474-df668a3527be.png)
![deployment faild 03](https://user-images.githubusercontent.com/111067796/187033835-499d50e1-2a34-4077-829a-64079b20c02e.png)
![deploayment faild 02](https://user-images.githubusercontent.com/111067796/187033838-ad61e3cc-e4d6-4632-aa26-22d5a60ea2e2.png)

and here is the error >>>
![error](https://user-images.githubusercontent.com/111067796/187033855-c038764a-78eb-443e-a748-ef8403929589.png)

 thanks , for your help

**Comment by microsoftman** [comment]
Hi @Camouflagestudios thanks for the details. We believe we have a fix to avoid this in the future, we are notifying Epic on so they can republish the fix.  I'll let you know when it's live.

**Comment by Camouflagestudios** [comment]
> Hi @Camouflagestudios thanks for the details. We believe we have a fix to avoid this in the future, we are notifying Epic on so they can republish the fix. I'll let you know when it's live.

Thanks alot . And cant wait to try the modified version

**Comment by microsoftman** [comment]
@Camouflagestudios Epic deployed a new release that should fix this issue--can you test your desired region(s) now?  Also, keep in mind, you'll want to check to make sure you have Quota in the region you are deploying too, which is best seen in Azure Portal->Subscriptions-><sub>->Usage and Quotas. For instance, in your pictures you used West US 3 for the shared Resource Group, and then East US for the GPU deployments, which was showing an A10 GPU that in high demand and would require a ticket likely to get access to that. Currently whatever first region you choose as the Region on the first Basics tab is what the available GPU SKUs are shown in the SKU picker, which we are looking at a better experience for this.  So if you choose West US 3 as the first region where the shared resources are deployed, and choose East US in the next tab for where to deploy the GPUs, the first page will only show West US 3 available SKUs--just as an FYI.  So it's recommend to choose the same region for both options in the beginning as you test.
