### ISSUE TITLE
NV6adsv5 VMs launch without required NVIDIA drivers

### ISSUE THREAD

**Issue by Zeyad-Alo** [Azure/Unreal-Pixel-Streaming#32]
When using Azure's Unreal Pixel Streaming using a UE5 package and deployed on **NV6adsv5** GPU VMs, the VM instances are launched without the required NVIDIA drivers and hence the stream fails to start on launch. I had to connect to the instances and manually install NVIDIA's GRID drivers for it work.

This is unexpected as it explicitly says on the marketplace that the features include " * Automatic installation of prerequisites for the VMs (i.e., VC++, DirectX, Node.js, **GPU drivers**, etc.)".

So is this a common issue or is it limited to the NV6adsv5 VMs, and is there a fix for it?

**Comment by microsoftman** [comment]
Hi @Zeyad-Alo, thanks for reporting this.  This is just specific to the A10 GPUs.  We have a base image with drivers and other software/pre-reqs installed when it was created, and it appears we need to update the latest drivers on that base image for A10's.  We'll work on getting that completed.

**Comment by Zeyad-Alo** [comment]
Yeah I figured it was the A10's only that were missing their compatible drivers after some digging, would be great to have them updated for the A10's as well though. Thanks a lot.

**Comment by microsoftman** [comment]
Yes the Marketplace version works now, as Epic was able to deploy a new base image for the VMSS nodes with the updated NVIDIA drivers.  We still need to do the same for our image used for Terraform.  Hopefully that should be done in the near future. In the mean time, I believe it should work if you point the Terraform base image to Epic's offer that was just published with the drivers -- do you want to verify that? We might just point this one to theirs in the future so we don't have to manage two base images.

Base VM Offer image used for the GPU (Virtual Machine Scale Set) nodes, which has UE pre-reqs and NVIDIA drivers pre-installed to speed up deployment:
Publisher: epicgames
Offer: unreal-pixel-streamer-vm
Sku: unreal-pixel-streamer-vm-plan

**Comment by microsoftman** [comment]
Just to update on this, we've found that we need to be using Windows Server 2022 instead of 2019 in order for nanite to work in UE5 (2019 doesn't support the latest drivers for DX12 Agility support). We are in testing phase currently, and will update when 2022 is ready with the latest drivers.

**Comment by microsoftman** [comment]
This is now resolved, and we use Windows Server 2022 instead of 2019 to allow for the DX12 Agility support.
