### ISSUE TITLE
Exception and terraform.tfvars is Missing

### ISSUE THREAD

**Issue by saadkan** [Azure/Unreal-Pixel-Streaming#6]
Hi, I am trying to follow the docs but I am stuck at terraForm part. 
When I run command `terraform apply -var 'git-pat=PUT_GIT_PAT_HERE' --auto-approve` I get following Error

````
│ Error: Variables not allowed
│
│   on <value for var.deployment_regions> line 1:
│   (source code not available)
│
│ Variables may not be used here.
╵
╷
│ Error: No value for required variable
│
│   on variables.tf line 40:
│   40: variable "deployment_regions" {
│
│ The root module input variable "deployment_regions" is not set, and has no default value. Use a -var or -var-file command line argument to
│ provide a value for this variable.
````

I am not expert in Azure and I am just following the docs so any help would be appreciated. Thanks.

**Comment by microsoftman** [comment]
Hi @saadkan, are you running this in PowerShell and inside the iac\ folder root? Also, did you fork this repo and then use your git-pat to replace the PUT_GIT_PAT_HERE text with your token? There's something funky about doing that command with that variable formatting in a DOS console window, so per the docs be sure to use PowerShell.

**Comment by saadkan** [comment]
@microsoftman Thanks for the response. I will pull latest commit. Yes I am using my git-pat. I have made separate repository for that and I am in powershell. Do I need to make SS, MM and VMSS manually before doing all that?

**Comment by saadkan** [comment]
@microsoftman Hi, I am still getting the same error. I don't what I am missing here. What is ` var.deployment_regions
  Enter a value:` error? What should I write here?

**Comment by saadkan** [comment]
@microsoftman Okay Its resolved now. I think the docs needs to be updated. In the [docs](https://github.com/Azure/Unreal-Pixel-Streaming#deployment) It is mentioned that `Delete the terraform.tfstate file in the iac\ folder if existing from a previous deployment.` but its needed in the process. That's why I was getting error. 

Although there is another problem that when Im opening MM VM in browser it always says `All Cirrus servers are in use. Retrying in 10 seconds.` For that I will make another issue. Thanks for updated repo before @microsoftman

**Comment by microsoftman** [comment]
Hi @saadkan, glad you got it figured out.  If you are starting a brand new deployment, you'll want to delete the tfstate file so that it doesn't interview with a new deployment. The var.deployment_regions was missing likely because there was that existing tfstate file from before when the tfvars file was missing. Per you question above, no you shouldn't need to do anything manually for the SS/MM, as the Terraform and PowerShell scripts setup everything for you--should be ready to run once you deploy.
